# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
GoodChoice.destroy_all
BadChoice.destroy_all

GoodChoice.create(image: "https://cdn1-www.dogtime.com/assets/uploads/2011/03/puppy-development.jpg", points: 5, result: "You chose to pet a cute puppy! Gain 5 points.", resultImage: "https://cdn.psychologytoday.com/sites/default/files/styles/image-article_inline_full/public/field_blog_entry_teaser_image/puppy_0.jpg?itok=z4JZm548")
GoodChoice.create(image: "https://images-na.ssl-images-amazon.com/images/I/71jtbb7QsUL._SY355_.jpg", points: 5, result: "You chose to help an elderly woman cross the street, and now she'll introduce you to her attractive, single son/daughter! Gain 5 points.", resultImage: "http://sharingwellnesswithfriends.com/wp-content/uploads/2014/07/happy-elderly-woman.jpg")
GoodChoice.create(image: "https://hwyspy.com/wp-content/uploads/2014/02/axe-hitch-hiker.jpg", points: 5, result: "You offered to drive a nice lumberjack to work. Gain 5 points.", resultImage: "https://ak4.picdn.net/shutterstock/videos/3254584/thumb/3.jpg")
GoodChoice.create(image: "https://bloximages.chicago2.vip.townnews.com/thesunchronicle.com/content/tncms/assets/v3/editorial/3/56/35611816-bf7a-5de2-b967-10f2580663e8/52cfa518526c3.image.jpg?resize=400%2C519", points: 5, result: "You helped a cat stuck in a tree! Gain 5 points.", resultImage: "http://gardenmentors.com/wp-content/uploads/2011/09/2011_arborist_cat_tree.png")
GoodChoice.create(image: "https://timesofindia.indiatimes.com/thumb/msid-68523832,width-800,height-600,resizemode-4/68523832.jpg", points: 5, result: "You chose to pet a cute kitten! Gain 5 points.", resultImage: "https://img.webmd.com/dtmcms/live/webmd/consumer_assets/site_images/article_thumbnails/video/caring_for_your_kitten_video/650x350_caring_for_your_kitten_video.jpg")
GoodChoice.create(image: "https://img.bleacherreport.net/img/images/photos/003/823/325/hi-res-2e148f9b3f3e4b3a13e44375bad339f7_crop_north.jpg?h=533&w=800&q=70&crop_x=center&crop_y=top", points: 5, result: "You chose the GREATEST OF ALL TIME. Gain 5 points.", resultImage: "https://images.complex.com/complex/images/c_limit,dpr_auto,q_90,w_720/fl_lossy,pg_1/anhjc627c6ixm9wayi0s/tom-brady-smiling")
GoodChoice.create(image: "https://www.thewrap.com/wp-content/uploads/2019/12/baby-yoda-soup.jpg", points: 5, result: "You chose to hang out with Baby Yoda. Gain 5 points.", resultImage: "https://i0.wp.com/metro.co.uk/wp-content/uploads/2019/11/PRI_98489049.jpg?quality=90&strip=all&zoom=1&resize=644%2C362&ssl=1")
GoodChoice.create(image: "https://suitesculturelles.files.wordpress.com/2015/04/parks-and-recreation-season-1-1-pilot-leslie-knope-ann-perkins-tom-haverford-amy-poehler-rashida-jones-aziz-ansari.jpg", points: 5, result: "You helped Leslie Knope build a park! Gain 5 points.", resultImage: "https://api.time.com/wp-content/uploads/2014/04/478221211.jpg?w=600&quality=85")
GoodChoice.create(image: "https://si.wsj.net/public/resources/images/B3-FF667_callce_P_20191016134739.jpg", points: 5, result: "You were nice to a telemarketer. Gain 5 points.", resultImage: "https://www.openaccessbpo.com/wp-content/uploads/2018/01/excited-call-center-agents.png")


BadChoice.create(image: "https://i.kym-cdn.com/entries/icons/facebook/000/004/473/free-candy.jpg", points: -5, result: "You chose the sketchy candy van?! Lose 5 points.", resultImage: "https://s.hdnux.com/photos/44/44/32/9586345/4/920x920.jpg")
BadChoice.create(image: "https://www.gannett-cdn.com/-mm-/5f7bdd12ee2b0ad63dfa2413a55fdaa0962a9ac2/c=171-0-2828-1998/local/-/media/2017/09/05/WIGroup/Milwaukee/636402201333255119-MCT-ENTER-IT-MOVIE-REVIEW-MCT-60586037.JPG?width=540&height=405&fit=crop", points: -5, result: "You took a balloon from a murderous clown. Lose 5 points.", resultImage: "https://hips.hearstapps.com/digitalspyuk.cdnds.net/17/38/1505731747-pennywise-teeth-it-movie.jpg?crop=0.563xw:1.00xh;0.136xw,0&resize=480:*")
BadChoice.create(image: "https://i.ytimg.com/vi/fjoUS-A7LqQ/maxresdefault.jpg", points: -5, result: "You chose a blood-soaked elevator in a haunted hotel. Lose 5 points.", resultImage: "https://media0.giphy.com/media/J4V0cmwb0xInC/giphy.gif")
BadChoice.create(image: "http://t.fod4.com/t/6e8fefeb3c/c480x270_50.jpg", points: -5, result: "You chose an ex-con who stole, robbed, and kidnapped the President's son. Lose 5 points.", resultImage: "https://i.pinimg.com/originals/38/a3/cb/38a3cb055a40c2692f648c59c93ba30c.jpg")
BadChoice.create(image: "https://images.fatherly.com/wp-content/uploads/2018/06/file.jpg?q=65&enable=upscale&w=600", points: -5, result: "You chose to pet a fiercesome velociraptor. Lose 5 points.", resultImage: "https://i0.wp.com/www.boingboing.net/filesroot/141_velociraptor.jpg?resize=500%2C343")
BadChoice.create(image: "https://www.pressdemocrat.com/csp/mediapool/sites/dt.common.streams.StreamServer.cls?STREAMOID=b6KFAehH8LTZ4EJMfB_Ys8$daE2N3K4ZzOUsqbU5sYva_XQ3t5bNrH5qiQY1QsFiWCsjLu883Ygn4B49Lvm9bPe2QeMKQdVeZmXF$9l$4uCZ8QDXhaHEp3rvzXRJFdy0KqPHLoMevcTLo3h8xh70Y6N_U_CryOsw6FTOdKL_jpQ-&CONTENTTYPE=image/jpeg", points: -5, result: "You chose to talk to one of the worst literary characters that ever existed. Lose 5 points.", resultImage: "http://www.the-leaky-cauldron.org/wp-content/uploads/assets/Dolores-umbridge-mean.jpg")
BadChoice.create(image: "https://i.dailymail.co.uk/1s/2019/12/09/20/22022440-7773679-image-a-1_1575922380561.jpg", points: -5, result: "You chose to eat E. coli - contaminated romaine lettuce. Lose 5 points.", resultImage: "https://media.boingboing.net/wp-content/uploads/2018/11/1600px-Stack_of_romaine_lettuce_heads.jpg")
BadChoice.create(image: "https://i.cbc.ca/1.4157138.1497292999!/fileImage/httpImage/image.jpg_gen/derivatives/16x9_780/nickelback-photograph.jpg", points: -5, result: "You willfully chose to listen to a Nickleback song. Lose 5 points.", resultImage: "https://sm.mashable.com/t/mashable_me/news/d/donald-tru/donald-trump-tweeted-a-nickelback-meme-and-we-should-all-jus_yrvf.960.jpg")
BadChoice.create(image: "https://www.unilad.co.uk/wp-content/uploads/2016/04/b39b9770-c0cd-0131-a022-1eba5a1de0f5.jpg", points: -5, result: "You chose to help a kid who would later turn to the Dark Side. Lose 5 points.", resultImage: "https://vignette.wikia.nocookie.net/5f6c0518-837d-4c4d-934e-1468490d076d/scale-to-width-down/800")
